# Generated by Django 3.1 on 2020-10-17 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='separation',
            old_name='Start',
            new_name='start',
        ),
    ]
