# Generated by Django 3.1.2 on 2020-10-31 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201017_0023'),
    ]

    operations = [
        migrations.DeleteModel(
            name='link',
        ),
    ]
